In [1]:
from numpy import *

In [70]:
#1
M = arange(1,10) * arange(1,10).reshape(-1,1)
M

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [71]:
#2
import numpy as np

def matrix(N, el1, d):
    progression = np.arange(el1, el1 + N * d, d)
    matrix = np.zeros((N, N))
    np.fill_diagonal(matrix, progression)
    return matrix

N = 7
el1 = 2.1
d = 3.7

itog_matrix = matrix(N, el1, d)
print(itog_matrix)


[[ 2.1  0.   0.   0.   0.   0.   0. ]
 [ 0.   5.8  0.   0.   0.   0.   0. ]
 [ 0.   0.   9.5  0.   0.   0.   0. ]
 [ 0.   0.   0.  13.2  0.   0.   0. ]
 [ 0.   0.   0.   0.  16.9  0.   0. ]
 [ 0.   0.   0.   0.   0.  20.6  0. ]
 [ 0.   0.   0.   0.   0.   0.  24.3]]


In [72]:
#3
data = genfromtxt('C:/Users/CoolerMaster/Downloads/stockholm_td_adj.dat')
data.shape

(77431, 7)

In [73]:
x = array([data[i,5] for i in range(data.shape[0]) if (data[i,0]==1970)*(data[i,1]==10)])

In [74]:
savetxt("oct70.bin", x)

In [75]:
savetxt("oct70.txt", x)

In [76]:
#4
A = array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [77]:
A[::1, ::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24],
       [30, 32, 34],
       [40, 42, 44]])

In [78]:
#5
chet_matrix = M[M % 3 == 0]
chet_matrix

array([ 3,  6,  9,  6, 12, 18,  3,  6,  9, 12, 15, 18, 21, 24, 27, 12, 24,
       36, 15, 30, 45,  6, 12, 18, 24, 30, 36, 42, 48, 54, 21, 42, 63, 24,
       48, 72,  9, 18, 27, 36, 45, 54, 63, 72, 81])

In [94]:
#7
M

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [109]:
v1 = M[1::2, ::2]
v1

array([[ 2,  6, 10, 14, 18],
       [ 4, 12, 20, 28, 36],
       [ 6, 18, 30, 42, 54],
       [ 8, 24, 40, 56, 72]])

In [110]:
v2 = M[::2, ::2]
v2

array([[ 1,  3,  5,  7,  9],
       [ 3,  9, 15, 21, 27],
       [ 5, 15, 25, 35, 45],
       [ 7, 21, 35, 49, 63],
       [ 9, 27, 45, 63, 81]])

In [113]:
values = np.array([v1, v2])

result = np.choose(v2, values)

result

C:\Users\CoolerMaster\AppData\Local\Temp\ipykernel_15184\1125266663.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array([v1, v2])


ValueError: invalid entry in choice array

In [125]:
#8
v1 = np.array([0, 1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8, 9])
s = dot(v1, v2)
s

80

In [126]:
l1 = linalg.norm(v1)
l2 = linalg.norm(v2)

In [127]:
result = s / (l1 * l2)

In [128]:
arccos(result) # в радианах

0.41613250096978566

In [170]:
#9
matrix1 = [[0 for i in range(5)] for j in range(5)]
matrix2 = [[0 if (i + j) % 2 == 0 else 5 for i in range(5)] for j in range(5)]
matrix2

[[0, 5, 0, 5, 0],
 [5, 0, 5, 0, 5],
 [0, 5, 0, 5, 0],
 [5, 0, 5, 0, 5],
 [0, 5, 0, 5, 0]]

In [171]:
for i in range(5):
    for j in range(5):
        if i == j or i < j:
            matrix1[i][j] = 5
matrix1

[[5, 5, 5, 5, 5],
 [0, 5, 5, 5, 5],
 [0, 0, 5, 5, 5],
 [0, 0, 0, 5, 5],
 [0, 0, 0, 0, 5]]

In [172]:
linalg.det(matrix1)

3124.999999999999

In [173]:
linalg.det(matrix2)

0.0

In [174]:
linalg.inv(matrix1)

array([[ 2.00000000e-01, -2.00000000e-01,  1.11022302e-17,
        -6.16297582e-34,  3.42113883e-50],
       [ 0.00000000e+00,  2.00000000e-01, -2.00000000e-01,
         1.11022302e-17, -6.16297582e-34],
       [ 0.00000000e+00,  0.00000000e+00,  2.00000000e-01,
        -2.00000000e-01,  1.11022302e-17],
       [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
         2.00000000e-01, -2.00000000e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e-01]])

In [175]:
linalg.inv(matrix2)

LinAlgError: Singular matrix